/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ense471lab1;

import java.awt.*;
import java.awt.Font;
import java.awt.Dimension;
import java.awt.Toolkit;

import javax.swing.*;

/**
 *
 * @author clayt
 */
public class ENSE471Lab1 extends javax.swing.JFrame
{

    /**
     * Creates new form ENSE471Lab1
     */
    public ENSE471Lab1()
    {
        // Define the title for the frame
        this.setTitle("Facebook");
        
        // Define the size of the frame
        this.setSize(500, 500);

        // open frame in the middle of the screen 
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dim = tk.getScreenSize();
        int xPos = (dim.width / 2) - (this.getWidth() / 2);
        int yPos = (dim.height / 2) - (this.getHeight() / 2);
        this.setLocation(xPos, yPos);
        
        this.setResizable(false);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        
        JPanel upperPanel = new JPanel();
        upperPanel.setBackground(Color.BLUE);
        upperPanel.setLayout(null); 
        upperPanel.setBounds(5, 5, 400, 50);
        
        // --- label ---
        JLabel labelA = new JLabel("Facebook");
        labelA.setFont(new Font("heading", 0, 20));
        labelA.setBounds(5, 5, 100, 50);
        upperPanel.add(labelA);
        
        // --- Button ---
        JButton button1 = new JButton("Signup");
        button1.setBackground(Color.GREEN);
        button1.setBounds(100, 25, 100, 20);
        upperPanel.add(button1);
        
        this.getContentPane().add(upperPanel);
        
        JPanel centerPanel = new JPanel();
        centerPanel.setBackground(Color.WHITE);
        centerPanel.setLayout(null);     
        centerPanel.setBounds(5, 55, 400, 350);
        
        // --- label ---
        JLabel label1 = new JLabel("Email or phone");
        centerPanel.add(label1);
        
        // --- text box ---
        JTextField textField1 = new JTextField();
        textField1.setColumns(25);
        centerPanel.add(textField1);

        // --- label ---
        JLabel label2 = new JLabel("Password");
        centerPanel.add(label2);
        
        // --- text box ---
        JTextField textField2 = new JTextField();
        textField2.setColumns(25);
        centerPanel.add(textField2);
        
        // --- label ---
        JLabel label3 = new JLabel("Keep me logged in");
        
        centerPanel.add(label3);
        
        // --- Button ---
        JButton button2 = new JButton("Login");
        centerPanel.add(button2);
        
        // --- label ---
        JLabel label4 = new JLabel("or Sign up for FaceBook                      ");
        //label4.setFont();
        centerPanel.add(label4);
        
        // --- label ---
        JLabel label5 = new JLabel("Forgot your password? ");
        //label3.label5();
        centerPanel.add(label5);
        
        this.getContentPane().add(centerPanel);
        

        // Make the frame show on the screen
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {

        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ENSE471Lab1().setVisible(true);
            }
        });

    }        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
